# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4577c9d36ed8b93914bcd00e4360b660d08fa8a40f771148beb3a84370fadcdf91e943fee6a4f4f89b4af555b9501db82f4d8989f05559e4261a410524f5bc55

test:
  secret_key_base: 5f29333e7ce7cf8b123efe705c5428bdcfbe2d8c1dbbb7b430b58201fd9ddd38f3c52a0be43c8c7c4db355825d4f4608998132a9fc5f5817b4324a7f8472363d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
